library(readr)
p<-read.csv('~/@IIITD/Semester 4/DBAP/DataforDBAsheet4.csv')
plot(p$year,p$sop)
plot(p$year,p$sos)
plot(p$year,p$tr)
plot(p$year,p$cop)
plot(p$year,p$cos)
plot(p$year,p$bcie)
plot(p$year,p$tcae)
plot(p$year,p$ifoi)
plot(p$year,p$gaae)
plot(p$year,p$rade)